Blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'articles'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.details, name='details'),
    path('add_article/', views.add_article, name='add_article'),
]

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    article_meta = models.CharField('Заголовок', max_length=50, null=True, blank=True)
    article_title = models.CharField('Название статьи', max_length=100)
    article_text = models.TextField('Текст статьи')
    pub_date = models.TextField('Дата публикации')  # TextField для русского отображения даты.
    article_image = models.ImageField(null=False, blank=True, upload_to='article_image')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):  # надо не совсем
        pass

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

articles/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse

from .models import Article
from datetime import datetime
import locale


# Create your views here.


def details(request):
    try:
        all_articles = Article.objects.all()[::-1][1:]
        last_article = Article.objects.all().order_by('-id')[0]
    except:
        return render(request, 'articles.html')

    return render(request, 'articles.html', {'all_articles': all_articles, 'last_article': last_article})


def add_article(request):
    locale.setlocale(locale.LC_ALL, "ru")
    try:
        Article.objects.create(article_meta=request.POST['article-meta'],
                               article_title=request.POST['article-title'],
                               article_text=request.POST['article-text'],
                               pub_date=datetime.today().strftime("%d %B %Y %H:%M"),
                               article_image=request.FILES['article-image'])
    except:
        return render(request, 'new_article.html')
    return HttpResponseRedirect(reverse('articles:details'))

articles/templates/articles.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    {% if last_article %}
        <section class="intro" id="intro"> {# LATEST ARTICLE #}
            <div class="container intro-container">
                <div class="intro-content">
                    <div class="intro-new">
                        <span class="intro-new__text">NEW</span>
                        <div class="intro-new__block">
                            <img src="{% static 'heart.svg' %}" alt="no image">
                            <span class="intro-new__block-num">25</span>
                        </div>
                        <div class="intro-new__block">
                            <img src="{% static 'message.svg' %}" alt="no image">
                            <span class="intro-new__block-num">25</span>
                        </div>
                        <div class="intro-new__block">
                            <img src="{% static 'eye.svg' %}" alt="no image">
                            <span class="intro-new__block-num">25</span>
                        </div>
                    </div>
                    <h1 class="intro__title">{{ last_article.article_title }}</h1>
                    <p class="intro__subtitle">{{ last_article.article_text }}</p>
                    <button class="intro__button">Читать</button>
                </div>
                <img src="{{ last_article.article_image.url }}" class="intro__img">
            </div>
        </section>
    {% endif %}
    {% if all_articles %}
        <section class="article" id="article">
            <div class="container">
                <div class="article-top">
                    <h1 class="article__title">Другие статьи</h1>
                    <button><img src="{% static 'filter.svg' %}"></button>
                </div>
                <div class="row">
                    {% for article in all_articles %}
                        <div class="col s4 article-block">
                            <span class="article__date">{{ article.pub_date }}</span>
                            <img src="{{ article.article_image.url }}" alt="no image" class="article-block__img">
                            {% if article.article_meta != None %}
                                <h2 class="article__name">{{ article.article_meta }}</h2>
                            {% endif %}
                            <a class="article__desc" href="#">{{ article.article_title }}</a>
                            <div class="article-new">
                                <div class="article-new__block">
                                    <img src="{% static 'heart.svg' %}" alt="no image">
                                    <span class="article-new__block-num">25</span>
                                </div>
                                <div class="article-new__block">
                                    <img src="{% static 'message.svg' %}" alt="no image">
                                    <span class="article-new__block-num">25</span>
                                </div>
                                <div class="article-new__block">
                                    <img src="{% static 'eye.svg' %}" alt="no image">
                                    <span class="article-new__block-num">25</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}

articles/templates/new_article.html
{% extends 'base.html' %}

{% block title %}Добавление статьи{% endblock %}
{% block header_text %}<a href="../../articles/">Блог</a> <span class="spliter">/</span>
    <a href="../add_article/">Добавить статью</a>{% endblock %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <section class="add" id="add">
        <div class="container">
            <h1 class="add__title">Добавить статью</h1>
            <form action="{% url 'articles:add_article' %}" method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="text" class="form__meta" placeholder="Введите заголовок статьи"
                       name="article-meta" required>
                <input type="text" class="form__input" placeholder="Введите название статьи"
                       name="article-title" required>
                <button class="form__btn" type="submit">Опубликовать</button>
                <br>
                <div class="form-bottom">
                    <textarea class="form__text" name="article-text" required></textarea>
                    <div class="form-file">
                        <span class="form-file__label">Загрузить изображение</span>
                        <label class="form-file-block">
                            <input type="file" class="form-file__input" id="fileIn" accept=".png, .jpg, .jpeg"
                                   name="article-image">
                            <span class="form-file__choose">Выбрать</span>
                            <div class="img">
                                <button class="form-file__close" type="button"><img src="{% static 'media/close.svg' %}"
                                                                                    alt="Закрыть"></button>
                            </div>
                        </label>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">

    <title>{% block title %}Блог{% endblock %}</title>
</head>
<body>
<header class="header" id="header"> {# HEADER #}
    <div class="header-left">
        <a href="base.html"><img src="{% static 'logo.png' %}" alt="Лого"></a>
        <a class="header-left__text" href="#">{% block header_text %}Блог{% endblock %}</a>
    </div>
    <div class="header-right">
        <a class="header-right__link" id="btn_add-article" href="add_article/">Добавить статью</a>
        <button><img src="{% static 'email.svg' %}" alt="email"></button>
        <button><img src="{% static 'uchenik.svg' %}" alt="email"></button>
        <button><img src="{% static 'logout.svg' %}" alt="email"></button>
    </div>
</header>
{% block content %}{% endblock %}
</body>
</html>